version: "3"

services:
  rabbitmq-container:
    build:
      context: ./../../../../
      dockerfile: src/main/resources/docker/rabbitmq/Dockerfile
    ports:
      - 5674:5672
      - 15674:15672
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  app-container:
    build:
      context: ./../../../../
      dockerfile: src/main/resources/docker/Dockerfile
    ports:
      - 8086:8086
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq-container
    depends_on:
      - rabbitmq-container